#!/usr/bin/env ruby


def usage()
    puts '    usage:'
    puts '        share | read $USER '
    exit 1
end

TMP_FILE = '~/.termshare'

# ============================================================================

if ARGV.length == 1 and ARGV[0] == 'share'
    puts 'share'
    `touch #{TMP_FILE}`
    `chmod a+r #{TMP_FILE}`
    if RUBY_PLATFORM.include? "darwin"
        exec('script -t0 #{TMP_FILE} bash')
    else
        exec('script -f #{TMP_FILE} bash')
    end
elsif ARGV.length == 2 and ARGV[0] == 'read'
    if RUBY_PLATFORM.include? "darwin"
        file = "/Users/#{ARGV[1]}/.termshare"
    else
        file = "/home/#{ARGV[1]}/.termshare"
    end
    if not File.exists? file
        puts "No shared terminal from '#{ARGV[1]}'"
        exit 1
    end
    puts "Reading from #{file}"
    exec('tail -f #{file}')
else
    usage()
end
